<a href="https://colab.research.google.com/github/Surajpanjiyar/Assignment-1-NumPy/blob/main/numpay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
 # Create a null vector of size 10 but the fifth value which is 1.

import numpy as np

null_vector = np.zeros(10)

null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
# Create a vector with values ranging from 10 to 49.

import numpy as np

vector = np.arange(10, 50)

print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# Create a 3x3 matrix with values ranging from 0 to 8.

import numpy as np

matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# Find indices of non-zero elements from [1,2,0,0,4,0].

import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(arr)

print(indices)


(array([0, 1, 4]),)


In [7]:
# Create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np

array = np.random.rand(10, 10)

min_value = np.min(array)
max_value = np.max(array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)


Minimum value: 0.02060390420240854
Maximum value: 0.9947086574511634


In [9]:
# Create a random vector of size 30 and find the mean value.

import numpy as np

random_vector = np.random.rand(30)

mean_value = np.mean(random_vector)

print("Mean value:", mean_value)


Mean value: 0.5075234371875597
